tiny_mtl:
  data_root: ../../../data/
  data_format: parquet
  train_data: ../../../data/all_seeds
  valid_data: ../../../data/all_seeds
  test_data: ../../../data/all_seeds
  train_size: 0.8
  valid_size: 0.1
  test_size: 0.1
  min_categr_count: 1
  feature_cols:
    [ { name: [ area_tag, age_tag, manufacture_tag, gender_tag, product, call_30_days_max_tag, call_30_days_min_tag, 
                call_30_days_most_tag, call_90_days_max_tag, call_90_days_min_tag, call_90_days_most_tag, call_total_max_tag, 
                call_total_min_tag, call_total_most_tag],
        active: True, dtype: str, type: categorical },
      { name: [algmodel_15_days_cnt, algmodel_30_days_cnt, algmodel_90_days_cnt, sms_total_click_cnt, sms_total_deliver_cnt,
               sms_180_days_click_cnt, sms_90_days_click_cnt, sms_30_days_click_cnt, sms_180_days_deliver_cnt, sms_90_days_deliver_cnt, 
               sms_30_days_deliver_cnt, call_total_deliver_cnt, call_total_click_cnt, call_180_days_sum_duration, call_90_days_sum_duration, 
               call_30_days_sum_duration, call_180_days_deliver_cnt, call_90_days_deliver_cnt, call_30_days_deliver_cnt, call_180_days_click_cnt, 
               call_90_days_click_cnt, call_30_days_click_cnt, hit_total_cnt, hit_180_days_hit_cnt, hit_90_days_hit_cnt, hit_60_days_hit_cnt, 
               hit_30_days_hit_cnt, hit_15_days_hit_cnt, hit_180_days_unhit_cnt, hit_90_days_unhit_cnt, hit_60_days_unhit_cnt, hit_30_days_unhit_cnt,
                hit_15_days_unhit_cnt, hit_180_days_product_cnt, hit_90_days_product_cnt, hit_60_days_product_cnt, hit_30_days_product_cnt, hit_15_days_product_cnt, 
                deliver_180_product_cnt, deliver_90_product_cnt, deliver_30_product_cnt, myhit_hit_180_days_cnt, myhit_hit_60_days_cnt, myhit_hit_30_days_cnt, 
                myhit_unhit_180_days_cnt, myhit_unhit_60_days_cnt, myhit_unhit_30_days_cnt, mymodel_cnt, reportmodel_360JT_sms_applyconverate_cnt,
                 reportmodel_360JT_sms_applyrate_cnt, reportmodel_360JT_sms_clickrate_cnt, reportmodel_360JT_sms_creditconverate_cnt, reportmodel_360JT_sms_creditrate_cnt,
                  reportmodel_360JT_sms_delivsum_cnt, reportmodel_360JT_sms_model_cnt, reportmodel_360JT_sms_pricerate_cnt, reportmodel_360JT_sms_regisconverate_cnt, 
                  reportmodel_360JT_sms_regrate_cnt, reportmodel_360JT_sms_roi_cnt, reportmodel_DDQ_sms_applyconverate_cnt, reportmodel_DDQ_sms_applyrate_cnt, 
                  reportmodel_DDQ_sms_clickrate_cnt, reportmodel_DDQ_sms_creditconverate_cnt, reportmodel_DDQ_sms_creditrate_cnt, reportmodel_DDQ_sms_delivsum_cnt, 
                  reportmodel_DDQ_sms_model_cnt, reportmodel_DDQ_sms_pricerate_cnt, reportmodel_DDQ_sms_regisconverate_cnt, reportmodel_DDQ_sms_regrate_cnt, 
                  reportmodel_DDQ_sms_roi_cnt, reportmodel_HB_sms_applyconverate_cnt, reportmodel_HB_sms_applyrate_cnt, reportmodel_HB_sms_clickrate_cnt, 
                  reportmodel_HB_sms_creditconverate_cnt, reportmodel_HB_sms_creditrate_cnt, reportmodel_HB_sms_delivsum_cnt, reportmodel_HB_sms_model_cnt, 
                  reportmodel_HB_sms_pricerate_cnt, reportmodel_HB_sms_regisconverate_cnt, reportmodel_HB_sms_regrate_cnt, reportmodel_HB_sms_roi_cnt, reportmodel_HFQ_sms_applyconverate_cnt, 
                  reportmodel_HFQ_sms_applyrate_cnt, reportmodel_HFQ_sms_clickrate_cnt, reportmodel_HFQ_sms_creditconverate_cnt, reportmodel_HFQ_sms_creditrate_cnt, reportmodel_HFQ_sms_delivsum_cnt,
                   reportmodel_HFQ_sms_model_cnt, reportmodel_HFQ_sms_pricerate_cnt, reportmodel_HFQ_sms_regisconverate_cnt, reportmodel_HFQ_sms_regrate_cnt, reportmodel_HFQ_sms_roi_cnt,
                    reportmodel_XHF_sms_applyconverate_cnt, reportmodel_XHF_sms_applyrate_cnt, reportmodel_XHF_sms_clickrate_cnt, reportmodel_XHF_sms_creditconverate_cnt, 
                    reportmodel_XHF_sms_creditrate_cnt, reportmodel_XHF_sms_delivsum_cnt, reportmodel_XHF_sms_model_cnt, reportmodel_XHF_sms_pricerate_cnt, 
                    reportmodel_XHF_sms_regisconverate_cnt, reportmodel_XHF_sms_regrate_cnt, reportmodel_XHF_sms_roi_cnt, reportmodel_XYF_sms_applyconverate_cnt, 
                    reportmodel_XYF_sms_applyrate_cnt, reportmodel_XYF_sms_clickrate_cnt, reportmodel_XYF_sms_creditconverate_cnt, reportmodel_XYF_sms_creditrate_cnt, 
                    reportmodel_XYF_sms_delivsum_cnt, reportmodel_XYF_sms_model_cnt, reportmodel_XYF_sms_pricerate_cnt, reportmodel_XYF_sms_regisconverate_cnt, 
                    reportmodel_XYF_sms_regrate_cnt, reportmodel_XYF_sms_roi_cnt, reportmodel_YQG_sms_applyconverate_cnt, reportmodel_YQG_sms_applyrate_cnt,
                     reportmodel_YQG_sms_clickrate_cnt, reportmodel_YQG_sms_creditconverate_cnt, reportmodel_YQG_sms_creditrate_cnt, reportmodel_YQG_sms_delivsum_cnt,
                      reportmodel_YQG_sms_model_cnt, reportmodel_YQG_sms_pricerate_cnt, reportmodel_YQG_sms_regisconverate_cnt, reportmodel_YQG_sms_regrate_cnt, 
                      reportmodel_YQG_sms_roi_cnt, reportmodel_YXH_sms_applyconverate_cnt, reportmodel_YXH_sms_applyrate_cnt, reportmodel_YXH_sms_clickrate_cnt, 
                      reportmodel_YXH_sms_creditconverate_cnt, reportmodel_YXH_sms_creditrate_cnt, reportmodel_YXH_sms_delivsum_cnt, reportmodel_YXH_sms_model_cnt, 
                      reportmodel_YXH_sms_pricerate_cnt, reportmodel_YXH_sms_regisconverate_cnt, reportmodel_YXH_sms_regrate_cnt, reportmodel_YXH_sms_roi_cnt, reportmodel_ZAXD_sms_applyconverate_cnt, 
                      reportmodel_ZAXD_sms_applyrate_cnt, reportmodel_ZAXD_sms_clickrate_cnt, reportmodel_ZAXD_sms_creditconverate_cnt, reportmodel_ZAXD_sms_creditrate_cnt, reportmodel_ZAXD_sms_delivsum_cnt, 
                      reportmodel_ZAXD_sms_model_cnt, reportmodel_ZAXD_sms_pricerate_cnt, reportmodel_ZAXD_sms_regisconverate_cnt, reportmodel_ZAXD_sms_regrate_cnt, reportmodel_ZAXD_sms_roi_cnt],
        active: True, dtype: float, type: numeric },
        {name:[appInstalls, outerBizSorted, outerModelCleanSorted, click_180_days_product_textlist, click_90_days_product_textlist, click_30_days_product_textlist, deliver_180_days_product_textlist,
         deliver_90_days_product_textlist, deliver_30_days_product_textlist],
        active: True, dtype: list, type: sequence, max_len:15, encoder: MaskedAveragePooling} 
        ]
  label_col: [ { name: label_register, dtype: float },
               { name: label_apply, dtype: float },
               { name: label_credit, dtype: float }
                  ]
