Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

M3oE_test:
    model: M3oE
    dataset_id: all_seeds_processed
    loss: [binary_crossentropy, binary_crossentropy]
    metrics: [AUC, KS, recall, precision, f1]
    task: [binary_classification, binary_classification]
    num_tasks: 2
    optimizer: adam
    learning_rate: 1.e-3
    embedding_regularizer: 1.e-8
    net_regularizer: 0
    batch_size: 128
    embedding_dim: 4
    epochs: 1
    shuffle: True
    seed: 2019
    monitor: AUC
    monitor_mode: max
    verbose: 1

    # M3oE specific
    num_domains: 9
    domain_feature: product
    expert_num: 4
    expert_hidden_units: [128, 64, 64]
    tower_hidden_units: [32]
    exp_d: 0.1
    exp_t: 0.1
    bal_d: 0.1
    bal_t: 0.1
    tau: 1
    tau_step: 0.00005
    softmax_type: 3
